### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by charbelhass** [k42b3/fusio#12]
Hello,

Finished running Fusio successfully. But I can't use the username and password created and generated using the php bin/fusio adduser command, http://localhost/fusio/public/backend.htm replies with Authentication failed
I tried to inspect the page. An error occurred:  
POST http://localhost/index.php/backend/token 404 (Not Found)(anonymous function) @ fusio.min.js:125m @ fusio.min.js:121f @ fusio.min.js:118(anonymous function) @ fusio.min.js:150m.$eval @ fusio.min.js:164m.$digest @ fusio.min.js:161m.$apply @ fusio.min.js:165(anonymous function) @ fusio.min.js:255c @ fusio.min.js:70

Please Help
Thanks in advance

**Comment by k42b3** [comment]
Hi, the problem is probably that the backend app cant determine the correct fusio API url. You could open the file "backend.htm" with an editor and hardcode the endpoint url i.e.:

    var fusio_url = 'http://localhost/fusio/public/index.php/';

Then if you login the request should go to http://localhost/fusio/public/index.php/backend/token which should work.
