### ISSUE TITLE
SQLFetchAll

### ISSUE THREAD

**Issue by Wakie87** [k42b3/fusio#14]
Using SQLFetchAll to access a database that has columns with headers that contain "_" (underscores) creates nested statements when not needed.

PSX\Util\CurveArray; - uses "underscore" as a sperator, 

Changing

return $this->response->build(200, [], [
$key => CurveArray::nest($result), 
 
To

return $this->response->build(200, [], [
$key => $result,

Fixes the problem.

**Comment by k42b3** [comment]
Hi, yes the intention was to provide an option to create nested results by simply using an "_". But this is not always the desired behaviour. We probably remove this behaviour from the SQL adapter and add a general action which provides rules to transform an response into another format. The best thing you could do now is to copy the code from the SQLFetchAll  adapter and create your own adapter (which simply does not use the CurveArray). In this way you can update Fusio without breaking any things.
