### ISSUE TITLE
Change default response

### ISSUE THREAD

**Issue by Wakie87** [k42b3/fusio#15]
The default output is xml, I know you can change the output by using "?format=json" in the url. But is it possible to set the default output anywhere? Say in the config file?

Thanks

**Comment by k42b3** [comment]
Hi, so the "default" output is actually json, in case you provide no informations what data you want to receive. If you visit an endpoint with a browser the browser sends an "Accept" header containing "application/xml". Because of this Fusio returns then xml. As work around you can specify in your "container.php" file explicit what writer classes you want support i.e.:

```php
$container = new Fusio\Impl\Dependency\Container();
$container->setParameter('config.file', __DIR__ . '/configuration.php');

// overwrite writer factory
$writer = new PSX\Data\WriterFactory();
$writer->addWriter(new PSX\Data\Writer\Json(), 0);

$container->set('writer_factory', $writer);

return $container;
```

Now Fusio can only write JSON data thus you would receive also JSON if you visit an endpoint with a browser.

That being said for the next release we may also add a simple configuration parameter, like you suggested, where all this is done in the background.

**Comment by Wakie87** [comment]
Awesome. So now how would you undo this to go back to the default?

The output now has 2-3 extra blank rows above the xml now.

Scott

On Sat, May 28, 2016 at 5:19 PM, Christoph Kappestein <
notifications@github.com> wrote:

> Hi, so the "default" output is actually json, in case you provide no
> informations what data you want to receive. If you visit an endpoint with a
> browser the browser sends an "Accept" header containing "application/xml".
> Because of this Fusio returns then xml. As work around you can specify in
> your "container.php" file explicit what writer classes you want support
> i.e.:
>
> $container = new Fusio\Impl\Dependency\Container();$container->setParameter('config.file', __DIR__ . '/configuration.php');// overwrite writer factory$writer = new PSX\Data\WriterFactory();$writer->addWriter(new PSX\Data\Writer\Json(), 0);$container->set('writer_factory', $writer);return $container;
>
> Now Fusio can only write JSON data thus you would receive also JSON if you
> visit an endpoint with a browser.
>
> That being said for the next release we may also add a simple
> configuration parameter, like you suggested, where all this is done in the
> background.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/k42b3/fusio/issues/15#issuecomment-222298998>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA7hPf0BapYP9DQ7ZZQKJu1NL_RMASbkks5qGAilgaJpZM4IoFH->
> .
>



-- 
*Scott Wakefield*
*Systems Director*
m: 0418 835 372
t: 9321 6411
PO Box 7948
Cloisters Square, Perth 6850

*"Collaborative health care starts here"*
www.npclinics.com.au

Contact us today for your health care needs or to book your next pap smear
<info@NPCLINICS.COM.AU>

*This transmission is for the use of the intended recipient only and may
contain information that is confidential and/or privileged. If you are not
the intended recipient of this message please notify the sender and Nurse
Practitioner Clinics Australia on 08 9321 6411 or Fax: 9321 1920. You must
not disseminate copy or take any action in reliance on it and please delete
the material. Before you take any action based upon advice and/or
information contained in this email you should carefully consider the
information provided and consider obtaining relevant independent advice.
Nurse Practitioner Clinics Australia does not represent warrant or
guarantee that the integrity of this communication is free of errors,
virus, interception or interference.*

**Comment by k42b3** [comment]
Iam not sure whether I understand the question correct, but for the default behaviour you simply dont have to overwrite the "writer_factory". The extra lines may come from newlines after or before the PHP closing tags.

**Comment by k42b3** [comment]
With the new release we have a config option "psx_supported_writer" where it is possible to set the supported writers
